# EBM { #paleobeasts.EBM }

```python
EBM(
    forcing,
    state_variables=['T'],
    diagnostic_variables=['albedo', 'absorbed_SW', 'OLR', 'solar_incoming'],
    var_name='temperature',
    OLR=None,
    C=4,
    merid_diff=0,
    albedo=0.3,
)
```

Energy Balance Model (EBM) class

A simple model that describes the evolution of the temperature of the Earth's surface
as a function of the radiative balance between incoming solar radiation and outgoing longwave radiation. The model
is described by the following ordinary differential equation:

$C rac{dT}{dt} = (1 - lpha) rac{S_0}{4} - OLR$

where $C$ is the heat capacity of the Earth's surface, $lpha$ is the albedo, $S_0$ is the incoming solar radiation,
$OLR$ is the outgoing longwave radiation.

#TODO: implement meridional heat transport; currently limited to 0D

## Parameters {.doc-section .doc-section-parameters}

| Name                 | Type                            | Description                                                                                                                                                                                                                                                                  | Default                                              |
|----------------------|---------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------|
| forcing              | pb.Forcing                      | Object that provides the forcing at time t.                                                                                                                                                                                                                                  | _required_                                           |
| state_variables      | list                            | List of state variables for the model. Default is ['T'].                                                                                                                                                                                                                     | `['T']`                                              |
| diagnostic_variables | list                            | List of diagnostic variables for the model. Default is ['albedo', 'absorbed_SW', 'OLR', 'solar_incoming'].                                                                                                                                                                   | `['albedo', 'absorbed_SW', 'OLR', 'solar_incoming']` |
| var_name             | str                             | Name of the variable being modeled. Default is 'temperature'.                                                                                                                                                                                                                | `'temperature'`                                      |
| OLR                  | float or function or pb.Forcing | Function that calculates the outgoing longwave radiation as a function of temperature. Default is the Stefan-Boltzmann law with prad=650, ps=1000. To specify different values, pass OLR_func(pRad, ps) where pRad is the radiative pressure and ps is the surface pressure. | `None`                                               |
| C                    | float or callable or pb.Forcing | Heat capacity of the Earth's surface. Default is 4.                                                                                                                                                                                                                          | `4`                                                  |
| albedo               | float or function or pb.Forcing | Albedo of the Earth's surface. Default is 0.3.                                                                                                                                                                                                                               | `0.3`                                                |

## Notes {.doc-section .doc-section-notes}

Parameters may be constants, callables, or ``pb.Forcing`` objects. Callables can use
common signatures such as ``(t)``, ``(t, state)``, ``(t, state, model)``,
``(model, state)``, or ``(state)``.